\documentclass[11pt]{article}\usepackage[]{graphicx}\usepackage[]{color}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{bm}
\usepackage{url}
\usepackage{enumerate}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
\setlength\parindent{0pt}

\large \textbf{Lab 8: Inference for Proportions and Chi-Square Tests using R}\\
\normalsize \textbf{STAT 630, Fall 2021}\\


\textbf{Data set}: The General Social Survey (GSS) is a major survey that tracks American demographics, characteristics, and views on social and cultural issues.  It is conducted by the National Opinion Research Center (NORC) at the University of Chicago.\\  

The 2002 GSS data can be accessed from the \texttt{resampledata} library.  It contains the responses of 2765 participants.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hlstd{(resampledata)}
\hlkwd{data}\hlstd{(}\hlstr{"GSS2002"}\hlstd{)}
\end{alltt}
\end{kframe}
\end{knitrout}

Variable descriptions:
\begin{table}[ht]
\begin{tabular}{l|l}
\hline
Variable & Description\\
\hline
Region & Interview location\\
Gender &  Gender of respondent\\
Race & Race of respondent\\
Education &  Highest level of education\\
Marital &  Marital status\\
Religion &  Religious affiliation\\
Happy &  General happiness\\
Income &  Respondent's income\\
Politics & Political views\\
Marijuana &  Legalize marijuana?\\
Death Penalty &  Death penalty for murder?\\
OwnGun &  Have gun at home?\\
GunLaw &  Require permit to buy a gun?\\
Pres00 &  Whom did you vote for in the 2000 presidential election?\\
Postlife & Believe in life after death?\\
\end{tabular}
\end{table}

\textbf{Example: two proportion z-test and confidence interval}\\
Using this data, let's test the hypothesis that men and women differ in their beliefs in an afterlife.  Specifically, we are testing\\ 
$H_0$: $p_f = p_m$\\
$H_A$: $p_f \neq p_m$\\
where $p_f$ is the population proportion of females who believe in an afterlife, and $p_m$ is the population proportion of men who believe in an afterlife.\\
\clearpage

First, remove the missing data.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{index} \hlkwb{<-} \hlkwd{which}\hlstd{(}\hlkwd{is.na}\hlstd{(GSS2002}\hlopt{$}\hlstd{Gender)} \hlopt{|} \hlkwd{is.na}\hlstd{(GSS2002}\hlopt{$}\hlstd{Postlife))}
\hlstd{gender} \hlkwb{<-} \hlstd{GSS2002}\hlopt{$}\hlstd{Gender[}\hlopt{-}\hlstd{index]}
\hlstd{postlife} \hlkwb{<-} \hlstd{GSS2002}\hlopt{$}\hlstd{Postlife[}\hlopt{-}\hlstd{index]}
\end{alltt}
\end{kframe}
\end{knitrout}

Next, we can examine some contingency tables:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{addmargins}\hlstd{(}\hlkwd{table}\hlstd{(gender, postlife))}
\end{alltt}
\begin{verbatim}
##         postlife
## gender     No  Yes  Sum
##   Female   98  550  648
##   Male    138  425  563
##   Sum     236  975 1211
\end{verbatim}
\begin{alltt}
\hlkwd{prop.table}\hlstd{(}\hlkwd{table}\hlstd{(gender, postlife),} \hlkwc{margin}\hlstd{=}\hlnum{1}\hlstd{)}
\end{alltt}
\begin{verbatim}
##         postlife
## gender          No       Yes
##   Female 0.1512346 0.8487654
##   Male   0.2451155 0.7548845
\end{verbatim}
\end{kframe}
\end{knitrout}
The sample sizes are large enough in each cell (greater than 5), so the conditions for the $z$-test are satisfied.  Based on the table of row proportions, it appears that a higher proportion of females believe in an afterlife than males.  We can proceed with the hypothesis test to find out if this is statistically significant.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{n} \hlkwb{<-} \hlkwd{length}\hlstd{(postlife)}
\hlstd{n_f} \hlkwb{<-} \hlkwd{sum}\hlstd{(gender} \hlopt{==} \hlstr{"Female"}\hlstd{)}
\hlstd{n_m} \hlkwb{<-}  \hlkwd{sum}\hlstd{(gender} \hlopt{==} \hlstr{"Male"}\hlstd{)}
\hlcom{# sample proportion of females that believe in afterlife:}
\hlstd{phat_f} \hlkwb{<-} \hlkwd{sum}\hlstd{(gender} \hlopt{==} \hlstr{"Female"} \hlopt{&} \hlstd{postlife} \hlopt{==} \hlstr{"Yes"}\hlstd{)} \hlopt{/} \hlstd{n_f; phat_f}
\end{alltt}
\begin{verbatim}
## [1] 0.8487654
\end{verbatim}
\begin{alltt}
\hlcom{# sample proportion of males that believe in afterlife:}
\hlstd{phat_m} \hlkwb{<-} \hlkwd{sum}\hlstd{(gender} \hlopt{==} \hlstr{"Male"} \hlopt{&} \hlstd{postlife} \hlopt{==} \hlstr{"Yes"}\hlstd{)} \hlopt{/} \hlstd{n_m; phat_m}
\end{alltt}
\begin{verbatim}
## [1] 0.7548845
\end{verbatim}
\begin{alltt}
\hlcom{# pooled sample proportion}
\hlstd{phat} \hlkwb{<-} \hlkwd{sum}\hlstd{(postlife} \hlopt{==} \hlstr{"Yes"}\hlstd{)} \hlopt{/} \hlstd{n; phat}
\end{alltt}
\begin{verbatim}
## [1] 0.8051197
\end{verbatim}
\end{kframe}
\end{knitrout}
\clearpage

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# compute test statistic}
\hlstd{SE} \hlkwb{<-} \hlkwd{sqrt}\hlstd{(phat}\hlopt{*}\hlstd{(}\hlnum{1}\hlopt{-}\hlstd{phat)}\hlopt{*}\hlstd{(}\hlnum{1}\hlopt{/}\hlstd{n_f} \hlopt{+} \hlnum{1}\hlopt{/}\hlstd{n_m))}
\hlstd{z} \hlkwb{<-} \hlstd{(phat_f} \hlopt{-} \hlstd{phat_m)} \hlopt{/} \hlstd{SE; z}
\end{alltt}
\begin{verbatim}
## [1] 4.1137
\end{verbatim}
\begin{alltt}
\hlcom{# p-value}
\hlstd{pvalue} \hlkwb{<-}  \hlnum{2} \hlopt{*} \hlstd{(}\hlnum{1} \hlopt{-} \hlkwd{pnorm}\hlstd{(z)); pvalue}
\end{alltt}
\begin{verbatim}
## [1] 3.893671e-05
\end{verbatim}
\end{kframe}
\end{knitrout}


The result is highly significant.  We reject $H_0$ since the $p$-value $\approx 0$.  Conclusively, the data suggest that men and women differ in their views of an afterlife.\\

Next, let's calculate a 95\% confidence interval for the difference between the proportion of males and females who believe in an afterlife:
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{SE} \hlkwb{<-} \hlkwd{sqrt}\hlstd{(phat_f}\hlopt{*}\hlstd{(}\hlnum{1}\hlopt{-}\hlstd{phat_f)}\hlopt{/}\hlstd{n_f} \hlopt{+} \hlstd{phat_m}\hlopt{*}\hlstd{(}\hlnum{1}\hlopt{-}\hlstd{phat_m)}\hlopt{/}\hlstd{n_m)}
\hlstd{ci_l} \hlkwb{<-} \hlstd{phat_f} \hlopt{-} \hlstd{phat_m} \hlopt{-} \hlnum{1.96} \hlopt{*} \hlstd{SE}
\hlstd{ci_u} \hlkwb{<-} \hlstd{phat_f} \hlopt{-} \hlstd{phat_m} \hlopt{+} \hlnum{1.96} \hlopt{*} \hlstd{SE}
\hlkwd{round}\hlstd{(}\hlkwd{c}\hlstd{(ci_l, ci_u),} \hlnum{3}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.049 0.139
\end{verbatim}
\end{kframe}
\end{knitrout}
We are 95\% confident that the population proportion of females who believe in an afterlife is between 0.049 and 0.139 higher than the population proportion of males who believe in an afterlife.\\
\clearpage

\textbf{Example: chi-square test for independence}\\
Going back to the example from lecture:\\
$H_0:$ Education and position on death penalty are independent.\\
$H_A:$ Education and position on death penalty are not independent.\\

First, let's examine some contingency tables:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{education} \hlkwb{<-} \hlstd{GSS2002}\hlopt{$}\hlstd{Education}
\hlstd{death_penalty} \hlkwb{<-} \hlstd{GSS2002}\hlopt{$}\hlstd{DeathPenalty}
\hlkwd{addmargins}\hlstd{(}\hlkwd{table}\hlstd{(education, death_penalty))}
\end{alltt}
\begin{verbatim}
##            death_penalty
## education   Favor Oppose  Sum
##   Left HS     117     72  189
##   HS          511    200  711
##   Jr Col       71     16   87
##   Bachelors   135     71  206
##   Graduate     64     50  114
##   Sum         898    409 1307
\end{verbatim}
\begin{alltt}
\hlkwd{prop.table}\hlstd{(}\hlkwd{table}\hlstd{(education, death_penalty),} \hlkwc{margin}\hlstd{=}\hlnum{1}\hlstd{)}
\end{alltt}
\begin{verbatim}
##            death_penalty
## education       Favor    Oppose
##   Left HS   0.6190476 0.3809524
##   HS        0.7187060 0.2812940
##   Jr Col    0.8160920 0.1839080
##   Bachelors 0.6553398 0.3446602
##   Graduate  0.5614035 0.4385965
\end{verbatim}
\end{kframe}
\end{knitrout}

We can use the function \texttt{chisq.test()} to implement the chi-square test for independence.  Note that this function will automatically remove any missing data.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{chisq1} \hlkwb{<-} \hlkwd{chisq.test}\hlstd{(education, death_penalty)}
\hlstd{chisq1}
\end{alltt}
\begin{verbatim}
## 
## 	Pearson's Chi-squared test
## 
## data:  education and death_penalty
## X-squared = 23.451, df = 4, p-value = 0.0001029
\end{verbatim}
\end{kframe}
\end{knitrout}
The chi-square test statistic is 23.45 with a p-value $=0.0001029$.  Since the $p$-value $<0.05$ we reject $H_0$, and conclude that the survey provides convincing evidence that education level and position on the death penalty are not independent.  Note that the results from the R function are the same as the manual computations on the lecture slides.\\

The object \texttt{chisq1} also has attributes that we can extract by name.  
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{attributes}\hlstd{(chisq1)}
\end{alltt}
\begin{verbatim}
## $names
## [1] "statistic" "parameter" "p.value"   "method"    "data.name" "observed" 
## [7] "expected"  "residuals" "stdres"   
## 
## $class
## [1] "htest"
\end{verbatim}
\begin{alltt}
\hlcom{# test statistic}
\hlstd{chisq1}\hlopt{$}\hlstd{statistic}
\end{alltt}
\begin{verbatim}
## X-squared 
##  23.45093
\end{verbatim}
\begin{alltt}
\hlcom{# p-value}
\hlstd{chisq1}\hlopt{$}\hlstd{p.value}
\end{alltt}
\begin{verbatim}
## [1] 0.0001028891
\end{verbatim}
\begin{alltt}
\hlcom{# table of expected counts}
\hlstd{chisq1}\hlopt{$}\hlstd{expected}
\end{alltt}
\begin{verbatim}
##            death_penalty
## education       Favor    Oppose
##   Left HS   129.85616  59.14384
##   HS        488.50650 222.49350
##   Jr Col     59.77506  27.22494
##   Bachelors 141.53634  64.46366
##   Graduate   78.32594  35.67406
\end{verbatim}
\end{kframe}
\end{knitrout}


% \clearpage
% 
% \large

% \textbf{Exercise} (in class): Does the 2002 GSS survey provide evidence of an association between marital status and general happiness?  To find out, conduct a chi-square test of independence between the variables \texttt{Marital} and \texttt{Happy}.   Write down the null and alternative hypotheses and your conclusion based on the $p$-value.  Also, check the conditions for the test.
% 
% <<echo=F, eval=F>>=
% happy <- GSS2002$Happy
% marital <- GSS2002$Marital
% addmargins(table(marital, happy))
% prop.table(table(marital, happy), margin = 1)
% chi1 <- chisq.test(marital, happy)
% chi1
% chi1$expected
% @


\end{document}
